# Generated by Django 2.0.4 on 2018-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
